name: mongodb
replicas: 1

image:
  repository: mongo
  tag: "7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

storage: 10Gi

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
