apiVersion: v2
name: app-stack
description: Umbrella chart for the application stack
version: 0.1.0
type: application

dependencies:
  - name: web
    version: "0.1.0"
    repository: "file://charts/web"

  - name: mongodb
    version: "0.1.0"
    repository: "file://charts/mongodb"

  - name: network-policy
    version: "0.1.0"
    repository: "file://charts/network-policy"
