replicaCount: 2

strategy:
  maxUnavailable: 0
  maxSurge: 1

image:
  repository: app_python-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: app.example.com

env:
  mongoTimeoutMs: "2000"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi