apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    app: {{ include "mongodb.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: {{ include "mongodb.fullname" . }}